#!/bin/sh
echo "✅ Running ktlintFormat..."
./gradlew ktlintFormat

echo "✅ Running ktlintCheck..."
./gradlew ktlintCheck

# ✅ 실패 시 커밋 중단
if [ $? -ne 0 ]; then
  echo "❌ ktlint check failed. Commit aborted."
  exit 1
fi