name: CI – ktlint only

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  ktlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Run ktlintCheck
        run: ./gradlew ktlintCheck
